server:
  port:
    6060

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matching?serverTimezone=Asia/Seoul
    #    url: jdbc:mysql://mysql_container:3306/matching?serverTimezone=Asia/Seoul
    #    username: ${MYSQL_NAME}
    #    password: ${MYSQL_PASSWORD}
    username: root
    password: 1234

  data:
    redis:
      sentinel:
        master:
          host: localhost
          port: 6379
        nodes:
          - localhost:26379
          - localhost:26380
          - localhost:26381
      timeout: 10000


management:
  endpoints:
    web:
      exposure:
        include: "*"







