server:
  port:
    6060

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST_IP}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RABBITMQ_URL}
    username: ${RABBITMQ_AWS_MYSQL_USERNAME}
    password: ${RABBITMQ_AWS_MYSQL_PASSWORD}

  data:
    redis:
      sentinel:
        master:
          host: ${REDIS_HOST_IP}
          port: 6379
        nodes:
          - ${REDIS_HOST_IP}:26379
          - ${REDIS_HOST_IP}:26380
          - ${REDIS_HOST_IP}:26381
      timeout: 10000


management:
  endpoints:
    web:
      exposure:
        include: "*"







